version: '3.4'

services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: world_volunteer_network
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        volumes:
        - ./postgres_data:/var/lib/postgresql/data/
    
        

